version: 0.1.{build}
image: Previous Visual Studio 2015
configuration:
- Release
- Debug
platform: x64
build:
  project: openthread.sln
  verbosity: minimal
test:
  assemblies: build\bin\$(configuration)\dll\UnitTests.dll