version: 0.1.{build}
image: Previous Visual Studio 2015
configuration:
- Release
- Debug
platform:
- x64
- x86
clone_depth: 10
build:
  project: openthread.sln
  verbosity: minimal
test:
  assemblies: build\bin\$(Platform)\$(Configuration)\dll\UnitTests.dll