version: 0.1.{build}
image: Previous Visual Studio 2015
configuration:
- Release
- Debug
platform:
- x64
- x86
clone_depth: 10
build:
  project: openthread.sln
  verbosity: minimal
after_build:
- cmd: echo %Platform%
- cmd: echo %cd%
- cmd: dir build\bin\
- cmd: dir build\bin\%Platform%\%Configuration%\dll\

test:
  assemblies: build\bin\$(Platform)\$(Configuration)\dll\UnitTests.dll

on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
