version: 1.0.{build}
image: Previous Visual Studio 2015
configuration:
- Release
- Debug
platform: x64
build:
  project: openthread.sln
  verbosity: minimal
test_script:
- cmd: >-
    .\.bin\x64\$CONFIGURATION$\exe\aes.exe

    .\.bin\x64\$CONFIGURATION$\exe\hmac_sha256.exe

    .\.bin\x64\$CONFIGURATION$\exe\link_quality.exe

    .\.bin\x64\$CONFIGURATION$\exe\lowpan.exe

    .\.bin\x64\$CONFIGURATION$\exe\mac_frame.exe

    .\.bin\x64\$CONFIGURATION$\exe\message.exe

    .\.bin\x64\$CONFIGURATION$\exe\ncp_buffer.exe

    .\.bin\x64\$CONFIGURATION$\exe\timer.exe

    .\.bin\x64\$CONFIGURATION$\exe\toolchain.exe